-- RODAR DEPOIS DE SUBIR O SISTEMA E CHAMAR TODOS OS METODOS QUE POPULA A BASE --

ALTER SEQUENCE seq_cliente RESTART WITH 1000;

ALTER SEQUENCE seq_motoboy RESTART WITH 1000;

ALTER SEQUENCE seq_cidade RESTART WITH 3;

ALTER SEQUENCE seq_estabelecimento RESTART WITH 1000;

ALTER SEQUENCE seq_produto RESTART WITH 1000;
